name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: astral-sh/ruff-action@v1
        name: Check Format
        with:
          args: "format --check --verbose"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: astral-sh/ruff-action@v1
        name: Check Lint
        with:
          args: "check --no-fix --verbose"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: "true"
          cache-suffix: "${{ matrix.python-version }}"
          cache-dependency-glob: 'uv.lock'

      - name: Install Dependencies
        run: uv sync --python "${{ matrix.python-version }}" --all-extras --dev

      - name: Run tests
        run: uv run --python "${{ matrix.python-version }}" pytest --cov=tests/ --cov-report term-missing